# See: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md
site_name: MyNotes
site_description: Add a short project description here.
site_author: Shubham Mishra
repo_url: https://github.com/subhmmisra/my_notes_be

nav:
- Home: index.md

- API:
  - 'Overview': api/0-overview.md
  - 'Notes': api/1-notes.md

- Backend:
  - 'Coding Rules': backend/coding_rules.md
- Release Notes: release_notes.md